import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const C=document.querySelector('#c'),R=new THREE.WebGLRenderer({canvas:C,antialias:true});R.setPixelRatio(Math.min(devicePixelRatio,2));R.outputColorSpace=THREE.SRGBColorSpace;const S=new THREE.Scene(),cam=new THREE.PerspectiveCamera(42,1,.1,500);cam.position.set(0,3,10);const ctl=new OrbitControls(cam,C);ctl.enableDamping=true;ctl.minDistance=4.8;ctl.maxDistance=17;
S.add(new THREE.AmbientLight(0x42506a,.18));const light=new THREE.PointLight(0xfff3d0,5);S.add(light);
let pts=[];for(let i=0;i<1800;i++){let r=30+Math.random()*35,a=Math.random()*6.28,z=Math.random()*2-1,s=Math.sqrt(1-z*z);pts.push(r*s*Math.cos(a),r*z,r*s*Math.sin(a))}let sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));S.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.045})));
const sun=new THREE.Mesh(new THREE.SphereGeometry(.82,48,48),new THREE.MeshBasicMaterial({color:0xffca4d}));sun.position.x=-6;S.add(sun);S.add(new THREE.PointLight(0xfff1c5,4));
let op=[];for(let i=0;i<257;i++){let a=i/256*6.28;op.push(new THREE.Vector3(6*Math.cos(a),0,3.4*Math.sin(a)))}let ol=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(op),new THREE.LineBasicMaterial({color:0x49647f,transparent:true,opacity:.65}));S.add(ol);
const EG=new THREE.Group(),AX=new THREE.Group();S.add(EG);EG.add(AX);AX.rotation.z=THREE.MathUtils.degToRad(23.5);const earth=new THREE.Mesh(new THREE.SphereGeometry(1.7,64,64),new THREE.MeshStandardMaterial({color:0x287bb9,roughness:.9}));AX.add(earth);AX.add(new THREE.Mesh(new THREE.SphereGeometry(1.77,64,64),new THREE.MeshBasicMaterial({color:0x64d7ff,transparent:true,opacity:.09,side:THREE.BackSide})));
const grid=new THREE.Group();AX.add(grid);function lat(a,col=0x8ddcff,op=.2){let r=1.71*Math.cos(THREE.MathUtils.degToRad(a)),y=1.71*Math.sin(THREE.MathUtils.degToRad(a)),q=new THREE.Mesh(new THREE.TorusGeometry(r,.009,4,120),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:op}));q.rotation.x=Math.PI/2;q.position.y=y;grid.add(q)}[-60,-30,0,30,60].forEach(x=>lat(x));[-23.5,23.5].forEach(x=>lat(x,0xffd36a,.45));
const ax=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,4.8,10),new THREE.MeshBasicMaterial({color:0xff7070}));ax.rotation.z=Math.PI/2;AX.add(ax);
const mark=new THREE.Mesh(new THREE.SphereGeometry(.06,16,16),new THREE.MeshBasicMaterial({color:0xffe68a}));mark.position.x=1.72;AX.add(mark);
function textSprite(t,col='#e5f4ff'){let c=document.createElement('canvas');c.width=500;c.height=80;let x=c.getContext('2d');x.font='bold 32px Tahoma';x.textAlign='center';x.fillStyle=col;x.fillText(t,250,50);let tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;let s=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,transparent:true,depthTest:false}));s.scale.set(1.2,.2,1);return s}let el=textSprite('زمین');el.position.set(0,2.2,0);S.add(el);let sl=textSprite('خورشید','#ffe08a');sl.position.set(-6,-1.25,0);S.add(sl);
const cities=[['تهران',51],['گرینویچ',0],['پاریس',2],['نیویورک',-74],['مسکو',38],['توکیو',140]];let cg=new THREE.Group();AX.add(cg);cities.forEach(([n,l])=>{let p=new THREE.Mesh(new THREE.SphereGeometry(.045,10,10),new THREE.MeshBasicMaterial({color:0xff7585}));let a=THREE.MathUtils.degToRad(l);p.position.set(1.73*Math.cos(a),.4,1.73*Math.sin(a));cg.add(p)});
let running=true,speed=1,da=0,ya=Math.PI/2,view='rotation';const data={rotation:['حرکت وضعی','چرا روز و شب به وجود می‌آید؟','۲۴ ساعت'],revolution:['حرکت انتقالی','زمین چگونه به دور خورشید حرکت می‌کند؟','۱ سال'],seasons:['فصل‌ها','چرا فصل‌ها به وجود می‌آیند؟','۲۳٫۵°'],time:['اختلاف ساعت','چرا ساعت شهرها یکسان نیست؟','۱۵° ≈ ۱ ساعت']};
function time(h){h=(h%24+24)%24;let a=Math.floor(h),b=Math.floor((h-a)*60);return String(a).padStart(2,'0')+':'+String(b).padStart(2,'0')}
function update(){document.querySelector('#mode').textContent=data[view][0];document.querySelector('#heading').textContent=data[view][1];document.querySelector('#big').textContent=view==='rotation'?time(12+da/6.283*24):data[view][2];document.querySelector('#day').textContent='روز '+(Math.round((((ya%(2*Math.PI))+2*Math.PI)%(2*Math.PI))/(2*Math.PI)*365)||1);let f=document.querySelector('#facts');f.innerHTML=view==='seasons'?'<div><b>تیر</b><span>روزهای بلندتر نیمکره شمالی</span></div><div><b>دی</b><span>روزهای کوتاه‌تر نیمکره شمالی</span></div><div><b>اعتدال</b><span>روز و شب تقریباً برابر</span></div>':view==='time'?'<div><b>۳۶۰°</b><span>یک دور زمین</span></div><div><b>۲۴ ساعت</b><span>یک شبانه‌روز</span></div><div><b>۱۵°</b><span>تقریباً یک ساعت</span></div>':`<div><b>${data[view][2]}</b><span>مقیاس اصلی این بخش</span></div><div><b>۳۶۰°</b><span>یک دور کامل</span></div><div><b>۲۳٫۵°</b><span>انحراف محور</span></div>`;let box=document.querySelector('#citylist');box.className='citygrid';box.innerHTML=cities.map(([n,l])=>`<div class="city"><b>${n}</b><span>${l>=0?l+'° شرقی':Math.abs(l)+'° غربی'}</span><time>${time(12+da/6.283*24+l/15)}</time></div>`).join('')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.v;document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');update()});document.querySelector('#play').onclick=()=>{running=!running;document.querySelector('#play').textContent=running?'❚❚ توقف':'▶ اجرا'};document.querySelector('#speed').oninput=e=>{speed=+e.target.value;document.querySelector('#sv').textContent=speed+'×'};document.querySelector('#back').onclick=()=>ya-=.18;document.querySelector('#next').onclick=()=>ya+=.18;document.querySelector('#reset').onclick=()=>{da=0;ya=Math.PI/2;cam.position.set(0,3,10)};document.querySelector('#grid').onchange=e=>grid.visible=e.target.checked;document.querySelector('#axis').onchange=e=>ax.visible=e.target.checked;document.querySelector('#cities').onchange=e=>cg.visible=e.target.checked;document.querySelector('#labels').onchange=e=>{el.visible=e.target.checked;sl.visible=e.target.checked};document.querySelectorAll('.timeline button').forEach(b=>b.onclick=()=>{ya=+b.dataset.d*Math.PI/180;document.querySelectorAll('.timeline button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')});document.querySelector('#help').onclick=()=>document.querySelector('#modal').classList.remove('hide');document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.add('hide');
function resize(){let w=C.clientWidth,h=C.clientHeight;R.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix()}addEventListener('resize',resize);resize();let clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.05);if(running){da+=dt*speed*.85;ya+=dt*speed*.045}AX.rotation.y=da;let x=6*Math.cos(ya),z=3.4*Math.sin(ya);EG.position.set(x,0,z);el.position.set(x,2.2,z);sl.position.set(-6,-1.25,0);ctl.update();update();R.render(S,cam)}update();loop();
